apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gleafink-cert
  namespace: console
spec:
  secretName: gleafink-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: console.gleafink.com
  dnsNames:
    - console.gleafink.com